
on:
  push:
    paths-ignore:
      - "**/*.md"
      
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      
      - name: Push NuGet package
        run: |
          dotnet nuget install secure-file -ExcludeVersion

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'
          
      #- name: Build with Maven
      #  run: mvn -B package --file pom.xml
