
on:
  push:
    paths-ignore:
      - "**/*.md"
      
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@< version >
        with:
          java-version: 17
          maven-version: 3.9.8
          
      #- name: Build with Maven
      #  run: mvn -B package --file pom.xml
