
on:
  push:
    paths-ignore:
      - "**/*.md"
      
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 17
          maven-version: 3.9.8

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: '5.x'
          
      - run: nuget install secure-file -ExcludeVersion
      - run: ./secure-file/tools/secure-file.exe -decrypt jcp-2.0.40450-A.zip.enc -secret ${{ secrets.DIADOC_SIGNING_SECRET }}

      - name: Extract JCP from ZIP
        uses: ihiroky/extract-action@v1
        with:
          file_path: ./jcp-2.0.40450-A.zip

      - run: ls -la
        
          
      #- name: Build with Maven
      #  run: mvn -B package --file pom.xml
